/**
 * Standardizes completions from AI providers into a unified structure.
 * @param {string} text - Response text generated by the provider
 * @param {string} provider - Active provider key (e.g. 'gemini')
 * @param {string} model - Active model key
 * @param {number} executionTime - Request duration in milliseconds
 * @param {boolean} cached - Indicates if request resolved via cache
 * @param {number} estimatedTokens - Total estimated/actual tokens count
 * @param {string} conversationId - Associated conversation session ID
 * @returns {Object} Unified response payload
 */
export const formatAIResponse = (
  text = '', 
  provider = 'mock', 
  model = 'default', 
  executionTime = 0, 
  cached = false, 
  estimatedTokens = 0, 
  conversationId = ''
) => {
  return {
    answer: text,
    provider,
    model,
    executionTime,
    cached,
    estimatedTokens,
    conversationId
  };
};

export default formatAIResponse;
