/**
 * Standardizes completions from AI providers into a unified structure.
 * @param {string} text - Response text generated by the provider
 * @param {string} provider - Active provider key (e.g. 'openrouter')
 * @param {string} model - Active model key (e.g. 'openrouter/free')
 * @param {number} executionTime - Request duration in milliseconds
 * @param {boolean} cached - Indicates if request resolved via cache
 * @param {number} estimatedTokens - Total estimated/actual tokens count
 * @param {string} conversationId - Associated conversation session ID
 * @param {Object} details - Additional token metrics
 * @returns {Object} Unified response payload
 */
export const formatAIResponse = (
  text = '', 
  provider = 'openrouter', 
  model = 'openrouter/free', 
  executionTime = 0, 
  cached = false, 
  estimatedTokens = 0, 
  conversationId = '',
  details = {}
) => {
  return {
    answer: text,
    provider,
    model,
    executionTime,
    responseTime: executionTime,
    cached,
    estimatedTokens,
    promptTokens: details.promptTokens || 0,
    completionTokens: details.completionTokens || 0,
    totalTokens: details.totalTokens || estimatedTokens,
    conversationId
  };
};

export default formatAIResponse;

